<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

  
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ConsoleInk.Net" Version="0.1.6" />
    <PackageReference Include="PromptVit" Version="1.1.1" />
    <PackageReference Include="ReadLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources/agents.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Resources/agents/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
